### ISSUE TITLE
Why not use Lazy or Func

### ISSUE THREAD

**Issue by scott-xu** [vany0114/EF.DbContextFactory#1]
`MyController(Func<MyDbContext> factory)`

**Comment by scott-xu** [comment]
MyController(Func<MyDbContext> factory)

**Comment by vany0114** [comment]
Hi @scott-xu

Thanks for your question. There are few problems with Lazy initialization in multi-thread scenarios, the first one is by default _Lazy_ uses locks to ensure that only a single thread can initialize a `Lazy<T>` instance in a thread-safe manner, by the other hand if you specify `PublicationOnly` option, it creates a copy of the lazily initialized object on each thread so all threads use the same instance of the lazily initialized object, therefore this is a problem because you're sharing the DbContext instance. In the end, any of the Lazy options work with DbContext in multi-thread scenarios. Actually, there is a warning with _Lazy_: 

> Making the Lazy<T> object thread safe does not protect the lazily initialized object. If multiple threads can access the lazily initialized object, you must make its properties and methods safe for multithreaded access.

Regarding the _Func_ approach, that's actually what the **EF.DbContextFactory** does behind the scenes, it encapsulates itself the responsibility for the DbContext creation and also manages the way to resolve a factory with different DI frameworks, such as Ninject, Structuremap, Unity, etc each has their own way to inject a factory.

I hope the answer will be helpful.

**Comment by scott-xu** [comment]
Why I need `DbContextFactory`? I think `Func<MyDbContext>` is enough. I just need to tell my DI container how to resolve `Func<>` and `MyDbContext`.

**Comment by scott-xu** [comment]
Using `Func<MyDbContext>` is more generic than your DbContextFactory. Consider aboutb another short lived disposable object.

**Comment by vany0114** [comment]
Of course, you can do it over and over again, but reuse the code is not just copy and paste, the idea is to take advantage of the nuget package to effectively reuse code. EF.DbContextFactory solves a especific problem in a generic and easily way, in the end it's up to you if you want to copy and paste the same solution over the projects or solutions or just download a package and that's it... that's the idea with packages.

**Comment by scott-xu** [comment]
Ok, I see. You are providing extension methods to tell DI container how to resolve `Func<TDbContect>`. However, I think some DI container already knows how to resolve generic `Func<>`. Also you are not using DI container to resolve `TDbContext`.

**Comment by scott-xu** [comment]
Let’s take Ninject for example, with Ninject.Extendion.Factory, you don’t need to Bind `Func<TDbContect>`, and if you are using `TDbContext` with parameterless constructor, you don’t need to Bind `TDbContext` as well.

**Comment by vany0114** [comment]
Yes you're right, actually I made a test with that extension for Ninject, that's cool, but my point is the same, the idea is to create a generic and easy way for multiple DI containers and everyone has its own way to deal with factories...also I don't remember if with Ninject's Factory extension resolve the connection string when there are multiples in the web.config or with another name that is not the default one.

**Comment by scott-xu** [comment]
If you need to specify the connection string when construct the TDbContext, there’s no difference with other service registration with dependencies. 
For example, Bind YourDbContext ToSelf with constructor argument YourConnectionString

**Comment by vany0114** [comment]
Cool and thanks for the discussion, I got your point and I hope you got mine with this project, it tries to provide a generic and easy way to deal with factories of DbContext for multiple DI containers, that's the propose. Thanks for taking some time and review it.
